version: "3.9"
services:
  app:
    build:
      dockerfile: "deploy/Dockerfile"
      context: .
    environment:
      SPRING_R2DBC_URL: "r2dbc:postgresql://db:5432/testDb"
      SPRING_R2DBC_USERNAME: "someUser"
      SPRING_R2DBC_PASSWORD: "somePassword"
    ports:
      - "8080:8080"
  db:
    image: "postgres:17.4-alpine"
    restart: always
    environment:
      POSTGRES_DB: testDb
      POSTGRES_USER: someUser
      POSTGRES_PASSWORD: somePassword
    volumes:
      - "./src/main/resources/sql/schema.sql:/docker-entrypoint-initdb.d/01_init_schema.sql"
      - "./example/example_data.sql:/docker-entrypoint-initdb.d/02_example_data.sql.sql"
#    ports:
#      - "5432:5432"
