spring:
  application:
    name: ala-discounts

  r2dbc:
    url: "r2dbc:postgresql://localhost:5432/testDb"
    username: "someUser"
    password: "somePassword"
    pool:
      enabled: true
      initial-size: 20
      max-size: 50
